using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace BillSponsors
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class billStatus
    {

        private billStatusBill billField;

        /// <remarks/>
        public billStatusBill bill
        {
            get
            {
                return this.billField;
            }
            set
            {
                this.billField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class billStatusBill
    {

        private short billNumberField;

        private sbyte congressField;

        private string versionField;

        private System.DateTime introducedDateField;

        private billStatusBillItem[] cosponsorsField;

        private billStatusBillItem1[] sponsorsField;

        /// <remarks/>
        public short billNumber
        {
            get
            {
                return this.billNumberField;
            }
            set
            {
                this.billNumberField = value;
            }
        }

        /// <remarks/>
        public sbyte congress
        {
            get
            {
                return this.congressField;
            }
            set
            {
                this.congressField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime introducedDate
        {
            get
            {
                return this.introducedDateField;
            }
            set
            {
                this.introducedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public billStatusBillItem[] cosponsors
        {
            get
            {
                return this.cosponsorsField;
            }
            set
            {
                this.cosponsorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public billStatusBillItem1[] sponsors
        {
            get
            {
                return this.sponsorsField;
            }
            set
            {
                this.sponsorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class billStatusBillItem
    {

        private System.DateTime sponsorshipDateField;

        private string bioguideIdField;

        private string lastNameField;

        private string sponsorshipWithdrawnDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime sponsorshipDate
        {
            get
            {
                return this.sponsorshipDateField;
            }
            set
            {
                this.sponsorshipDateField = value;
            }
        }

        /// <remarks/>
        public string bioguideId
        {
            get
            {
                return this.bioguideIdField;
            }
            set
            {
                this.bioguideIdField = value;
            }
        }

        /// <remarks/>
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public string sponsorshipWithdrawnDate
        {
            get
            {
                return this.sponsorshipWithdrawnDateField;
            }
            set
            {
                this.sponsorshipWithdrawnDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class billStatusBillItem1
    {

        private string bioguideIdField;

        private string lastNameField;

        /// <remarks/>
        public string bioguideId
        {
            get
            {
                return this.bioguideIdField;
            }
            set
            {
                this.bioguideIdField = value;
            }
        }

        /// <remarks/>
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }



}
