//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("rollcall-vote", Namespace = "", IsNullable = false)]
public partial class rollcallvote
{

    private rollcallvoteVotemetadata votemetadataField;

    private rollcallvoteRecordedvote[] votedataField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-metadata")]
    public rollcallvoteVotemetadata votemetadata
    {
        get
        {
            return this.votemetadataField;
        }
        set
        {
            this.votemetadataField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("vote-data")]
    [System.Xml.Serialization.XmlArrayItemAttribute("recorded-vote", IsNullable = false)]
    public rollcallvoteRecordedvote[] votedata
    {
        get
        {
            return this.votedataField;
        }
        set
        {
            this.votedataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadata
{

    private string majorityField;

    private int congressField;

    private string sessionField;

    private string chamberField;

    private short rollcallnumField;

    private string legisnumField;

    private string votequestionField;

    private string votetypeField;

    private string voteresultField;

    private string actiondateField;

    private rollcallvoteVotemetadataActiontime actiontimeField;

    private string votedescField;

    private rollcallvoteVotemetadataVotetotals votetotalsField;

    /// <remarks/>
    public string majority
    {
        get
        {
            return this.majorityField;
        }
        set
        {
            this.majorityField = value;
        }
    }

    /// <remarks/>
    public int congress
    {
        get
        {
            return this.congressField;
        }
        set
        {
            this.congressField = value;
        }
    }

    /// <remarks/>
    public string session
    {
        get
        {
            return this.sessionField;
        }
        set
        {
            this.sessionField = value;
        }
    }

    /// <remarks/>
    public string chamber
    {
        get
        {
            return this.chamberField;
        }
        set
        {
            this.chamberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rollcall-num")]
    public short rollcallnum
    {
        get
        {
            return this.rollcallnumField;
        }
        set
        {
            this.rollcallnumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legis-num")]
    public string legisnum
    {
        get
        {
            return this.legisnumField;
        }
        set
        {
            this.legisnumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-question")]
    public string votequestion
    {
        get
        {
            return this.votequestionField;
        }
        set
        {
            this.votequestionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-type")]
    public string votetype
    {
        get
        {
            return this.votetypeField;
        }
        set
        {
            this.votetypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-result")]
    public string voteresult
    {
        get
        {
            return this.voteresultField;
        }
        set
        {
            this.voteresultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action-date")]
    public string actiondate
    {
        get
        {
            return this.actiondateField;
        }
        set
        {
            this.actiondateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action-time")]
    public rollcallvoteVotemetadataActiontime actiontime
    {
        get
        {
            return this.actiontimeField;
        }
        set
        {
            this.actiontimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-desc")]
    public string votedesc
    {
        get
        {
            return this.votedescField;
        }
        set
        {
            this.votedescField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vote-totals")]
    public rollcallvoteVotemetadataVotetotals votetotals
    {
        get
        {
            return this.votetotalsField;
        }
        set
        {
            this.votetotalsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadataActiontime
{

    private string timeetzField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("time-etz")]
    public string timeetz
    {
        get
        {
            return this.timeetzField;
        }
        set
        {
            this.timeetzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadataVotetotals
{

    private rollcallvoteVotemetadataVotetotalsTotalsbypartyheader totalsbypartyheaderField;

    private rollcallvoteVotemetadataVotetotalsTotalsbyparty[] totalsbypartyField;

    private rollcallvoteVotemetadataVotetotalsTotalsbyvote totalsbyvoteField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("totals-by-party-header")]
    public rollcallvoteVotemetadataVotetotalsTotalsbypartyheader totalsbypartyheader
    {
        get
        {
            return this.totalsbypartyheaderField;
        }
        set
        {
            this.totalsbypartyheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("totals-by-party")]
    public rollcallvoteVotemetadataVotetotalsTotalsbyparty[] totalsbyparty
    {
        get
        {
            return this.totalsbypartyField;
        }
        set
        {
            this.totalsbypartyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("totals-by-vote")]
    public rollcallvoteVotemetadataVotetotalsTotalsbyvote totalsbyvote
    {
        get
        {
            return this.totalsbyvoteField;
        }
        set
        {
            this.totalsbyvoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadataVotetotalsTotalsbypartyheader
{

    private string partyheaderField;

    private string yeaheaderField;

    private string nayheaderField;

    private string presentheaderField;

    private string notvotingheaderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("party-header")]
    public string partyheader
    {
        get
        {
            return this.partyheaderField;
        }
        set
        {
            this.partyheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("yea-header")]
    public string yeaheader
    {
        get
        {
            return this.yeaheaderField;
        }
        set
        {
            this.yeaheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nay-header")]
    public string nayheader
    {
        get
        {
            return this.nayheaderField;
        }
        set
        {
            this.nayheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("present-header")]
    public string presentheader
    {
        get
        {
            return this.presentheaderField;
        }
        set
        {
            this.presentheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("not-voting-header")]
    public string notvotingheader
    {
        get
        {
            return this.notvotingheaderField;
        }
        set
        {
            this.notvotingheaderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadataVotetotalsTotalsbyparty
{

    private string partyField;

    private short yeatotalField;

    private int naytotalField;

    private int presenttotalField;

    private int notvotingtotalField;

    /// <remarks/>
    public string party
    {
        get
        {
            return this.partyField;
        }
        set
        {
            this.partyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("yea-total")]
    public short yeatotal
    {
        get
        {
            return this.yeatotalField;
        }
        set
        {
            this.yeatotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nay-total")]
    public int naytotal
    {
        get
        {
            return this.naytotalField;
        }
        set
        {
            this.naytotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("present-total")]
    public int presenttotal
    {
        get
        {
            return this.presenttotalField;
        }
        set
        {
            this.presenttotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("not-voting-total")]
    public int notvotingtotal
    {
        get
        {
            return this.notvotingtotalField;
        }
        set
        {
            this.notvotingtotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteVotemetadataVotetotalsTotalsbyvote
{

    private string totalstubField;

    private short yeatotalField;

    private int naytotalField;

    private int presenttotalField;

    private int notvotingtotalField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("total-stub")]
    public string totalstub
    {
        get
        {
            return this.totalstubField;
        }
        set
        {
            this.totalstubField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("yea-total")]
    public short yeatotal
    {
        get
        {
            return this.yeatotalField;
        }
        set
        {
            this.yeatotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nay-total")]
    public int naytotal
    {
        get
        {
            return this.naytotalField;
        }
        set
        {
            this.naytotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("present-total")]
    public int presenttotal
    {
        get
        {
            return this.presenttotalField;
        }
        set
        {
            this.presenttotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("not-voting-total")]
    public int notvotingtotal
    {
        get
        {
            return this.notvotingtotalField;
        }
        set
        {
            this.notvotingtotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteRecordedvote
{

    private rollcallvoteRecordedvoteLegislator legislatorField;

    private string voteField;

    /// <remarks/>
    public rollcallvoteRecordedvoteLegislator legislator
    {
        get
        {
            return this.legislatorField;
        }
        set
        {
            this.legislatorField = value;
        }
    }

    /// <remarks/>
    public string vote
    {
        get
        {
            return this.voteField;
        }
        set
        {
            this.voteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rollcallvoteRecordedvoteLegislator
{

    private string nameidField;

    private string sortfieldField;

    private string unaccentednameField;

    private string partyField;

    private string stateField;

    private string roleField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("name-id")]
    public string nameid
    {
        get
        {
            return this.nameidField;
        }
        set
        {
            this.nameidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sort-field")]
    public string sortfield
    {
        get
        {
            return this.sortfieldField;
        }
        set
        {
            this.sortfieldField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("unaccented-name")]
    public string unaccentedname
    {
        get
        {
            return this.unaccentednameField;
        }
        set
        {
            this.unaccentednameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string party
    {
        get
        {
            return this.partyField;
        }
        set
        {
            this.partyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
